Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 140
Naming/UncommunicativeMethodParamName:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/BlockLength:
  Max: 45
Metrics/ClassLength:
  Max: 120